### ISSUE TITLE
stop adding me to your repo. it's annoying to get e-mails from you

### ISSUE THREAD

**Issue by quinnliu** [jacobtran2/cohort12-site#1]

**Comment by jacobtran2** [comment]
Sorry about that.

**Comment by misraelson** [comment]
??

On Mon, Apr 18, 2016 at 1:49 PM, Q <notifications@github.com> wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobtran2/cohort12-site/issues/1>
>



-- 
Regards,

Matthew Israelson
